# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0004_auto_20170106_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='UdpatePlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.BigIntegerField()),
                ('playList', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='update_playlist', to='musicwebsite.PlayList')),
            ],
        ),
    ]
