# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0005_udpateplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='playList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='musicwebsite.PlayList'),
        ),
    ]
