# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-08 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0007_song_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album_img',
        ),
        migrations.AddField(
            model_name='song',
            name='album_img_title',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
