# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0012_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='pos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='schoolOwner',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
