# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0014_song_singer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='schoolOwner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
