# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0015_auto_20170410_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.FileField(null=True, upload_to='ads/')),
                ('state', models.IntegerField(default=-1)),
            ],
        ),
    ]
