# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0016_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='img',
            field=models.ImageField(null=True, upload_to='ads/'),
        ),
    ]
