# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0017_auto_20170410_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ad_type',
            field=models.IntegerField(default=-1),
        ),
    ]
