# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicwebsite', '0018_ads_ad_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='url',
            field=models.CharField(default='', max_length=80),
        ),
    ]
